### ISSUE TITLE
Can't buid via Yarn

### ISSUE THREAD

**Issue by drkranger71** [ryceg/Eigengrau-s-Essential-Establishment-Generator#636]
$ yarn build generates a Syntax Error:

\Eigengrau-s-Essential-Establishment-Generator-master\src\main.ts: Missing semicolon. (54:7)

  52 | import { npcDeath, createDeadNPC } from './NPCGeneration/setupDeath'
  53 |
> 54 | declare global {
     |        ^
  55 |   interface Setup {
  56 |     createAlchemist: typeof createAlchemist
  57 |     brothelData: typeof brothelData
    at Parser._raise (\Eigengrau-s-Essential-Establishment-Generator-master\node_modules\@babel\parser\lib\index.js:807:17)
    at Parser.raiseWithData (\Eigengrau-s-Essential-Establishment-Generator-master\node_modules\@babel\parser\lib\index.js:800:17)
    at Parser.raise (\Eigengrau-s-Essential-Establishment-Generator-master\node_modules\@babel\parser\lib\index.js:761:17)
    at Parser.semicolon (\Eigengrau-s-Essential-Establishment-Generator-master\node_modules\@babel\parser\lib\index.js:9901:10)
    at Parser.parseExpressionStatement (\Eigengrau-s-Essential-Establishment-Generator-master\node_modules\@babel\parser\lib\index.js:13012:10)
    at Parser.parseStatementContent (\Eigengrau-s-Essential-Establishment-Generator-master\node_modules\@babel\parser\lib\index.js:12601:19)
    at Parser.parseStatement (\Eigengrau-s-Essential-Establishment-Generator-master\node_modules\@babel\parser\lib\index.js:12465:17)
    at Parser.parseBlockOrModuleBlockBody (\Eigengrau-s-Essential-Establishment-Generator-master\node_modules\@babel\parser\lib\index.js:13054:25)
    at Parser.parseBlockBody (\Eigengrau-s-Essential-Establishment-Generator-master\node_modules\@babel\parser\lib\index.js:13045:10)
    at Parser.parseProgram (\Eigengrau-s-Essential-Establishment-Generator-master\node_modules\@babel\parser\lib\index.js:12396:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11600) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11600) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 1.06s.

Not sure where a semicolon is supposed to go where it shows it's supposed to go.  Possible ghost character or false error, error somewhere else.

**Comment by ryceg** [comment]
Does `yarn start` work?

**Comment by drkranger71** [comment]
Error in same spot, but it doesn't die.

```
$ yarn start
yarn run v1.22.10
$ node scripts/build --watch
Compiling scripts...
Copying files...
Running tweego!
@rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
@rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
SyntaxError: \Eigengrau-s-Essential-Establishment-Generator-master\src\main.ts: Missing semicolon. (54:7)

  52 | import { npcDeath, createDeadNPC } from './NPCGeneration/setupDeath'
  53 |
> 54 | declare global {
     |        ^
  55 |   interface Setup {
  56 |     createAlchemist: typeof createAlchemist
  57 |     brothelData: typeof brothelData
SyntaxError: \Eigengrau-s-Essential-Establishment-Generator-master\lib\types.ts: Support for the experimental syntax 'flow' isn't currently enabled (6:8):

  4 |  * Returns the keys from `T` whose property types match the type `V`.
  5 |  */
> 6 | export type KeysMatching<T, V> = {
    |        ^
  7 |   [K in keyof T]-?: T[K] extends V ? K : never
  8 | }[keyof T]
  9 |

Add @babel/preset-flow (https://git.io/JfeDn) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-flow (https://git.io/vb4yb) to the 'plugins' section to enable parsing.

Watch mode started.  Press CTRL+C to stop.

Recursively watched paths: 1
  src

BUILDING: gh-pages\index.html

```

However index.html generates fatal errors.

Error: <<set>>: bad evaluation: Cannot set property 'ignoreGender' of undefined The $town.type of $town.name
Error: <<run>>: bad evaluation: Cannot read property 'name' of undefined

Error: <<set>>: bad evaluation: Cannot read property 'customImage' of undefined
Error: <<if>>: bad conditional expression in <<elseif>> clause (#1): Cannot read property 'localImage' of undefined
Error: <h1>: bad evaluation from attribute directive "@data-town-type": Cannot read property 'type' of undefinedThe
Error: <span>: bad evaluation from attribute directive "@data-town-type": Cannot read property 'type' of undefined
Error: <<print>>: bad evaluation: Cannot read property 'type' of undefined</span> of
Error: <span>: bad evaluation from attribute directive "@data-town-name": Cannot read property 'name' of undefined$town.name</span></h1>
Error: <span>: bad evaluation from attribute directive "@data-town-type": Cannot read property 'type' of undefined$town.name</span> is
Error: <<print>>: bad evaluation: lib is not defined located
Error: <<print>>: bad evaluation: lib is not defined the $town.terrain $town.location, where the vegetation is $town.vegetation. $town.name grew around $town.origin, and is comprised . They are
Error: <<if>>: bad conditional expression in <<if>> clause: Cannot read property 'ignoreGender' of undefined
Error: <<print>>: bad evaluation: lib is not defined
Error: <<print>>: bad evaluation: lib is not defined
Error: <<print>>: bad evaluation: lib is not defined that .

Detailed description of $town.name 
Error: <<listbox>>: bad evaluation: Cannot convert undefined or null to object — 
Error: <<for>>: bad range expression: Cannot read property 'roads' of undefined

**Comment by ryceg** [comment]
This is really strange, as I can't replicate this on my end. What version of Node are you using? Is this a fresh install?

**Comment by drkranger71** [comment]
Pulled latest version of code.
I'm using git bash to run the commands.
Yarn build dies in the same spot. 

Node.js: v14.16.1
yarn install v1.22.10

Running Yarn Test:
`$ yarn test
yarn run v1.22.10
$ jest
PASS lib/src/matchFirst.test.ts
PASS lib/src/defineRollDataGetter.test.ts
  ● Console

    console.groupCollapsed
        DefineRollDataGetters

      at Object.defineRollDataGetter (lib/src/defineRollDataGetter.ts:36:11)

    console.log
        [Arguments] {
        '0': {
          name: 'Test Tavern',
          roll: { wealth: 99 },
          wealth: undefined,
          rollData: { wealth: [Array] }
        },
        '1': [ [ 99, 'very solid' ], [ 90, 'solid' ], [ 50, 'not solid' ] ],
        '2': 'wealth'
      }

      at Object.defineRollDataGetter (lib/src/defineRollDataGetter.ts:39:11)

    console.log
      Fetching Test Tavern wealth.

      at Object.get [as wealth] (lib/src/defineRollDataGetter.ts:49:17)

    console.groupCollapsed
        DefineRollDataGetters

      at Object.defineRollDataGetter (lib/src/defineRollDataGetter.ts:36:11)

    console.log
        [Arguments] {
        '0': {
          name: 'Test Tavern',
          roll: { wealth: 95 },
          wealth: undefined,
          rollData: { wealth: [Array] }
        },
        '1': [ [ 99, 'very solid' ], [ 90, 'solid' ], [ 50, 'not solid' ] ],
        '2': 'wealth'
      }

      at Object.defineRollDataGetter (lib/src/defineRollDataGetter.ts:39:11)

    console.log
      Fetching Test Tavern wealth.

      at Object.get [as wealth] (lib/src/defineRollDataGetter.ts:49:17)

    console.groupCollapsed
        DefineRollDataGetters

      at Object.defineRollDataGetter (lib/src/defineRollDataGetter.ts:36:11)

    console.log
        [Arguments] {
        '0': {
          name: 'Test Tavern',
          roll: { wealth: -5 },
          wealth: undefined,
          rollData: { wealth: [Array] }
        },
        '1': [ [ 99, 'very solid' ], [ 90, 'solid' ], [ 50, 'not solid' ] ],
        '2': 'wealth'
      }

      at Object.defineRollDataGetter (lib/src/defineRollDataGetter.ts:39:11)

    console.log
      Fetching Test Tavern wealth.

      at Object.get [as wealth] (lib/src/defineRollDataGetter.ts:49:17)

    console.log
      Failed to get a descriptor that matched the roll of -5 for wealth.

      at Object.get [as wealth] (lib/src/defineRollDataGetter.ts:63:17)

PASS lib/npc-generation/createName.test.ts
  ● Console

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

    console.log
      Returning a name!

      at Object.createName (lib/npc-generation/createName.ts:14:11)

PASS lib/general-store/generalStoreRenders.test.ts
PASS lib/buildings/cullBuildings.test.ts
PASS lib/faction/createLivery.test.ts
PASS lib/npc-generation/getAgeInYears.test.ts
PASS lib/town/politicsWeightedRoll.spec.ts
PASS lib/tavern/createTavernName.spec.ts
PASS lib/src/sortArray.test.ts
PASS lib/src/utils.test.ts

Test Suites: 11 passed, 11 total
Tests:       25 passed, 25 total
Snapshots:   0 total
Time:        20 s
Ran all test suites.
Done in 31.57s.
`

**Comment by drkranger71** [comment]
As of 7/18/21, right now, whatever was changed in the most recent build fixed this issue.  I was able to build locally without issue.

**Comment by ryceg** [comment]
Huh, interesting. Thanks for letting me know!
